List canadianCityAndState = [
'Isle-morte, Manitoba',
'Loverna, Prince Edward Island',
'Marathon, Quebec',
'Savona, Newfoundland',
'Midland, New Brunswick',
'Kelso Station, Ontario',
'Flatbush, Nova Scotia',
'Scudder, Alberta',
'Princeton, Nunavut',
'Luscar, Nova Scotia',
'Belle River, Nunavut',
'Malonton, Saskatchewan',
'Ile Verte, Yukon',
'Stalwart, Nunavut',
'Wabowden, Manitoba',
'Dresden, Yukon',
'Riverside, Saskatchewan',
'Wekweti, Saskatchewan',
'La Scie, Alberta',
'Fort Grahame, Nova Scotia',
'Princeton, Manitoba',
'Rexmount, Quebec',
'Pendleton, Manitoba',
'Alexo, Manitoba',
'Sugluk, Alberta',
'Dartmouth, Prince Edward Island',
'Henley Harbour, Ontario',
'Front Of Escott, Newfoundland',
'Cranbrook, Yukon',
'Robinsons, Manitoba',
];
List usaCityAndState = [
'Holden, Idaho',
'Marion, New York',
'George, New York',
'Mount Freedom, Tennessee',
'Calumet Woods, Montana',
'Claresville, Hawaii',
'Arp, Pennsylvania',
'Brockwood, Montana',
'Pringle, Massachusetts',
'Owyhee, South Carolina',
'Stillwater, Maryland',
'Lakeview Resort, Arkansas',
'Sandy Fork, Florida',
'Head Of Island, Idaho',
'Stagecoach, South Carolina',
'Muscadine, Tennessee',
'Willow Crest, Minnesota',
'Glens Fork, Alabama',
'Savoyard, Connecticut',
'Deadfall Crossroads, Wyoming',
'Mantz, Idaho',
'Cotton Hill Gin Estates, Tennessee',
'Crossroads, Vermont',
'Auburn, Florida',
'Drybranch, Hawaii',
'Nortonsville, Kentucky',
'Bancroft, Connecticut',
'North Hills, Georgia',
'Midway, Colorado',
'Newhalen, Idaho',
];

List countryName = [
'Dominican Republic',
'Mozambique',
'Afghanistan',
'Egypt',
'Nepal',
'Mauritius',
'Bolivia',
'British Indian Ocean Territory',
'Italy',
'United States',
'Ethiopia',
'Solomon Islands',
'Bangladesh',
'Tajikistan',
'Saudi Arabia',
'Trinidad and Tobago',
'Croatia',
'Swaziland',
'Haiti',
'French Polynesia',
'Benin',
'Eritrea',
'Burundi',
'United Arab Emirates',
'Malaysia',
'Spain',
'Cape Verde',
'Kiribati',
'Comoros',
'Faroe Islands',
'Hungary',
'Republic of Macedonia',
'Romania',
'Australia',
'Denmark',
'Argentina',
'Guinea-Bissau',
'Sri Lanka',
'Bosnia and Herzegovina',
'Hong Kong',
'Mongolia',
'Bermuda',
'Guam',
'Austria',
'Moldova',
'Grenada',
'Greenland',
'Iceland',
'Curacao',
'Palau',
'Republic of Ireland',
'Ecuador',
'Japan',
'Liechtenstein',
'Philippines',
'Oman',
'Kenya',
'Honduras',
'New Caledonia',
'Virgin Islands (U.S.)',
'Latvia',
'Angola',
'North Korea',
'Greece',
'Ghana',
'Georgia',
'Taiwan',
'Marshall Islands',
'Cocos (Keeling) Islands',
'Netherlands',
'New Zealand',
'Serbia',
'United Kingdom',
'Sao Tome and Principe',
'Holy See',
'Democratic Republic of the Congo',
'Christmas Island',
'Antigua and Barbuda',
'Aland Islands',
'Martinique',
'Lithuania',
'Jordan',
'Scotland',
'Zambia',
'Mali',
'Maldives',
'Guadeloupe',
'Jamaica',
'Poland',
'Uzbekistan',
'Wales',
'Pakistan',
'Syria',
'Turkey',
'Colombia',
'Togo',
'Azerbaijan',
'Germany',
'Turks and Caicos Islands',
'Pitcairn Islands',
];

///list of cities or town from canada usa and india
///congo and france
List worldCitiesOrTown = 
[
'Brustico',
'Cadalen',
'Bonnieux',
'Genarville',
'Pinsot',
'Chilly',
'Norante',
'Jardres',
'Galié',
'Chapeau',
'Wasselonne',
'Thillois',
'Villesauveix',
'Abjat',
'Kisenzele',
'Bilota',
'Mipalala',
'Kamekuba',
'Benkuna',
'Dikida',
'Mvuila',
'Blliza',
'Boliebu',
'Lungoma',
'Yalilongo',
'Kidianga',
'Kasandzi',
'Ekanga',
'Kotobongo',
'Kondji',
'Fota',
'Kotalmanda',
'Chikalthana',
'Sundargarh',
'Akodha',
'Chunpura',
'Gokalpur',
'Gokal',
'Bhitindi',
'Bharusar',
'Chhapri',
'Gushi',
'Girisola',
'Hatiā',
'Tirkana',
'Panhech',
'Salotri',
'Amboli',
'Udamalpet',
'Lalauli',
'Sydenham',
'Kuujjuaq',
'Bowden',
'Balzac',
'Shawbridge',
'Chandindu',
'Sqatteck',
'Port Hastings',
'Killam',
'Duparquet',
'Stanmore',
'Kirriemuir',
'Donnacona',
'Shillington',
'Bissett',
'Zealandia',
'Washagami',
'Outlook',
'Merrit',
'Hilda',
'Holden',
'Frankford',
'Evergreen',
'Ramona',
'Sorrento',
'Quartz Hill',
'Otego',
'Whiteface',
'Robersonville',
'Portola',
'Lakeview North',
'Wadena',
'Coshocton',
'New Leipzig',
'Heidelberg',
'Krebs',
'Heathrow',
'Depew',
'Enon',
'North Platte',
'Eldorado Springs',
'Gulf Port',
'Byhalia',
'Lake',
'Menominee',
'Grand Isle',
'Loma',
];

List canadianCitiesOrTown = 
[
'Everard',
'Weenusk',
'Milverton',
'Emerald',
'Kincolith',
'Saint-Grègoire',
'Baldur',
'Goldboro',
'Penhold',
'Poularies',
];

List unitedStateCitiesOrTown = 
[
'Sherburn',
'Morgan\'s Point',
'Falls Creek',
'Littlerock',
'Sparks',
'Village of Grosse Pointe Shores',
'Chical',
'Inola',
'White Plains',
'Klamath Falls',
];