List restaurantName = [
  'Lonesome Dove',
  'Bobby’s',
  'Melting Pot',
  'Daytime Place',
  'Easy Eats',
  'Macro Bites',
  'Grubber Hub',
  'Cheerful Rhino',
  'Home Cooking Experience',
  'Fare & Feed',
  'Golden Palace',
  'Soups & Snacks',
  'Quick Bite',
  'Fast & Friendly',
  'Big Bites',
  'Blind Pig',
  'Eatable',
  'Eatery',
  'Goodies',
  'Lard Boy',
  'Many Foods',
  'Me Likey',
  'Wonton Express',
  'Great Burger',
  'Awesome Burger',
  'Amazing Sauce',
  'Asian Express',
  'Fearless Wander',
  'Crate Express',
  'Smothered In Love',
  'Sweet Delectable',
  'Appetizing As Heck',
  'Appetizing Bird',
  'Scrumptious Temptations',
  'Smile N\’ Delight',
  'Choice Foods',
  'Dainty Dog',
  'Hungry Dog',
  'Heavenly Creations',
  'Food For Thought',
  'Food In My Tummy',
  'Tum Tum Express',
  'Lil Johnny\’s',
  'Bill’s Burgers',
  'A Night In Paris',
  'Distinctive Creations',
  'Spicy Heat',
  'Spicy Jack\’s',
  'Pepper Jack\’s',
  'Rich Meat',
  'Fit For A King',
  'King of Meat',
  'Delicious Donuts',
  'Rare Meats',
  'Rare Cuts',
  'Rare Choice',
  'Sapid Salads',
  'Soup & Salad Express',
  'Seasoned',
  'Smitten',
  'Love Street',
  'Ice Cream Sandwiches',
  'For The Love Of Ice Cream',
  'Infatuated Creations',
  'Smack Dab',
  'Frozen Yogurt',
  'Sherbet',
  'Mickey\’s Foodstuff',
  'Pick & Go',
  'The Satiated Drink',
  'Pearl',
  'Bless This Mess Hall',
  'Grits & Gravy',
  'Cheerful Hippo',
  'Mealtime',
  'Summer’s End',
  'Winter Comes',
  'Nightcap',
  'It’s Good Food',
  'Leggo My Wagyu',
  'Tokyo Beat',
  'New York Pulse',
  'Chicago Style Pizza',
  'Hill Country Fare',
  'TidBits',
  'No Place Like Home',
  'Trial & Error',
  'Rinse & Repeat',
  'Cook & Boil',
  'Broiler',
  'Broiled Duck',
  'Prancing Pig',
  'Sweet Duck',
  'Aaron’s',
  'Salt & Snow',
  'Roaring Tiger',
  'Fig’s BBQ',
  'Odd Pig',
  'Southside',
  'Northend',
  'Roaring Ridgemont',
  'Tia’s Mexican Hut',
  'Atomic Good',
  'L’Gran',
  'Casa Del Rio',
  'Clio',
  'Bartholomew’s',
  'Villa',
  'Sushi Roll',
  'Hand Roll',
];
//====
List veganStarter = [
  'Strawberry and basil soup',
  'Squash and truffle soup',
  'Sweetcorn and vegan pesto dumplings',
  'Melon and pear soup',
  'Tofu and squash parcels',
  'Samphire and potato soup',
  'Spinach and coriander dumplings',
  'Cabbage and horseradish dumplings',
  'Nectarine and cardamom gyoza',
  'Cardamom and vanilla mousse',
];
List veganStarterDescription = [
  'Fresh strawberries and basil combined into smooth soup',
  'Fresh squash and truffle combined into smooth soup',
  'Thin pastry cases stuffed with baby sweetcorn and basil pesto',
  'Honeydew melon and dried pears combined into chunky soup',
  'Thin filo pastry cases stuffed with crispy tofu and acorn squash',
  'Samphire and new potato combined into chunky soup',
  'Thin pastry cases stuffed with fresh spinach and dried coriander',
  'Thin pastry cases stuffed with savoy cabbage and fresh horseradish',
  'Thin pastry cases stuffed with fresh nectarine and green cardamom',
  'A creamy mousse made with black cardamom and vanilla',
];
List veganStarterIngredient = [
  'garlic | strawberry | basil',
  'onion | squash | truffle',
  'flour | water | salt | onions | sweetcorn | vegan pesto',
  'onion | melon | pear',
  'flour | water | salt | onions | tofu | squash',
  'onion | samphire | potato',
  'flour | water | salt | onions | spinach | coriander',
  'flour | water | salt | onions | nectarine | cardamom',
  'avocado | coconut cream | onions | cardamom | vanilla | cream',
];
List veganMainMeal = [
  'Pumpkin and squash risotto',
  'Cabbage and sorrel soup',
  'Pepper and courgette bread',
  'Elderflower and vegan sweet mincemeat pie',
  'Sweetcorn and asafoetida curry',
  'Apple and persimmon gyoza',
  'Peanut and anise curry',
  'Cauliflower and banana korma',
  'Banana and avocado ciabatta',
  'Tofu and avocado toastie',
];
List veganMainMealDescription = [
  'Creamy risotto rice with spiced pumpkin and pattypan squash',
  'Fresh cabbage and sorrel combined into creamy soup',
  'Crunchy bread made with sweet pepper and fresh courgette',
  'A puff pasty case filled with elderflower and mincemeat',
  'Spicy curry made with baby sweetcorn and asafoetida',
  'Thin pastry cases stuffed with crab apple and fresh persimmon',
  'Hot curry made with peanut and fresh anise',
  'Creamy korma made with fresh cauliflower and banana',
  'Warm ciabatta filled with fresh banana and avocado',
  'Crisp slices of bread filled with silken tofu and fresh avocado'
];
List veganMainMealIngredient = [
  'olive oil | onion | garlic | spring onions | rice | cumin | parmesan | pumpkin | squash | cream',
  'onion | cabbage | sorrel | cream',
  'flour | salt | yeast | butter | water | onions | pepper | courgette',
  'flour | butter | water | salt | onions | elderflower | vegan sweet mincemeat',
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | curry leaf | green chilli | sweetcorn | asafoetida',
  'flour | water | salt | onions | apple | persimmon',
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | curry leaf | green chilli | peanut | anise',
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | butter | sugar | cream | cauliflower | banana',
  'flour | yeast | water | salt | sugar | oil | banana | avocado',
  'flour | yeast | water | salt | sugar | oil | tofu | avocado'
];

List veganSnacks = [
  'Kiwi fruit and mushroom dip',
  'Quince and ugli fruit jam',
  'Almond and spinach vegan vegan vegan vegan pancake',
  'Cabbage and tofu wontons',
  'Leek and parsley parcels',
  'Raspberry and bran buns',
  'Cardamom and currant loaf',
  'Rice and chilli cake',
  'Pomelo and vanilla jam',
  'Parsley and squash bread',
];
List veganSnacksDescription = [
  'A dip made from fresh kiwi fruit and crimini mushroom',
  'A rich jam made from fresh quince and ugli fruit',
  'Crispy vegan vegan vegan vegan vegan pancake filled with flaked almond and baby spinach',
  'Thin wonton cases stuffed with fresh cabbage and crispy tofu',
  'Thin filo pastry cases stuffed with fresh leek and flat-leaf parsley',
  'Crumbly buns made with fresh raspberry and bran',
  'Fluffy bread made with black cardamom and fresh currant',
  'Rich cake made with basmalti rice and dried chilli',
  'A sweet jam made from fresh pomelo and vanilla',
  'Fluffy bread made with fresh parsley and squash',
];
List veganSnacksIngredient = [
  'creme fraiche | kiwi fruit | mushroom',
  'flour | yeast | water | salt | sugar | oil | quince | ugli fruit',
  'flour | coconut butter | almond milk | almond | spinach',
  'flour | water | salt | onions | cabbage | tofu',
  'flour | water | salt | onions | leek | parsley',
  'flour | vegetable oil | sugar | raspberry | bran',
  'flour | salt | yeast | butter | water | onions | cardamom | currant',
  'flour | vegetable fat | sugar | rice | chilli',
  'flour | yeast | water | salt | sugar | oil | pomelo | vanilla',
  'flour | salt | yeast | butter | water | onions | parsley | squash'
];
//======
List vegetarianStarter = [
  'Persimmon and nectarine parcels',
  'Raspberry and banana cake',
  'Cheddar and leek loaf',
  'Parsnip and kohlrabi soup',
  'Spinach and cocoa pancake',
  'Grapefruit and egg panini',
  'Rhubarb and polenta bread',
  'Blueberry and cinnamon cupcakes',
  'Samphire and mustard soup',
  'Polenta and vanilla cake',
];
List vegetarianStarterDescription = [
  'Thin filo pastry cases stuffed with fresh persimmon and nectarine',
  'Rich cake made with fresh raspberry and banana',
  'Crunchy bread made with cheddar and fresh leek',
  'Fresh parsnips and kohlrabi combined into smooth soup',
  'Crispy pancake filled with baby spinach and cocoa',
  'A hot, pressed panini filled with fresh grapefruit and free range eggs',
  'Fluffy bread made with fresh rhubarb and polenta',
  'Rich cupcakes made with fresh blueberry and cinnamon',
  'Samphire and dijon mustard combined into smooth soup',
  'Rich cake made with polenta and vanilla',
];
List vegetarianStarterIngredients = [
  'flour | water | salt | onions | persimmon | nectarine',
  'flour | butter | egg | sugar | raspberry | banana',
  'flour | salt | yeast | butter | water | onions | cheddar | leek',
  'garlic | parsnip | kohlrabi',
  'flour | butter | egg | milk | spinach | cocoa',
  'flour | yeast | water | salt | sugar | oil | grapefruit | egg',
  'flour | salt | yeast | butter | water | onions | rhubarb | polenta',
  'flour | butter | egg | sugar | blueberry | cinnamon',
  'garlic | samphire | mustard',
  'flour | butter | egg | sugar | polenta | vanilla'
];
List vegetarianSnacks = vegetarianStarter;
List vegetarianSnacksDescription = vegetarianStarterDescription;
List vegetarianSnacksIngredients = vegetarianStarterIngredients;

List vegetarianMainMeal = [
  'Banana and asafoetida vindaloo',
  'Rice and sweet mincemeat pie',
  'Durian and mangetout salad',
  'Squash and pumpkin korma',
  ' Mango and pumpkin vindaloo',
  'Garam masala and spinach bread',
  'Avocado and cucumber bagel',
  'Aubergine and egg pasta',
  'Chestnut and buckwheat salad',
  'Squash and potato kebab',
];
List vegetarianMainMealDescription = [
  'Hot vindaloo made with fresh banana and asafoetida',
  'A shortcrust pasty case filled with long grain rice and mincemeat',
  'A crisp salad featuring fresh durian and mangetout',
  'Creamy korma made with pattypan squash and fresh pumpkin',
  'Spicy vindaloo made with dried mango and spiced pumpkin',
  'Fluffy bread made with garam masala and baby spinach',
  'A warm bagel filled with fresh avocado and cucumber',
  'Fresh egg pasta in a sauce made from chargrilled aubergine and free range eggs',
  'Roasted chestnut and buckwheat served on a bed of lettuce',
  'Skewer-cooked acorn squash and new potato served in warm pitta pockets',
];
List vegetarianMainMealIngredient = [
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | black pepper | mustard seeds | cardamon | cinnamon | white wine vinegar | cayenne | banana | asafoetida',
  'flour | butter | water | salt | onions | rice | sweet mincemeat',
  'lettuce | white cabbage | cucumber | durian | mangetout',
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | butter | sugar | cream | squash | pumpkin',
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | black pepper | mustard seeds | cardamon | cinnamon | white wine vinegar | cayenne | mango | pumpkin',
  'flour | salt | yeast | butter | water | onions | garam masala | spinach',
  'flour | yeast | water | salt | sugar | oil | avocado | cucumber',
  'tomato | onion | garlic | pasta | oregano | black pepper | aubergine | egg',
  'lettuce | chestnut | buckwheat',
  'onions | flour | yeast | water | salt | sugar | oil | squash | potato'
];

//=======
List nonVegetarianStarter = [
  'Lime and kohlrabi soup',
  'Ricotta and peppercorn gyoza',
  'Cheese and pheasant gyoza',
  'Cheese and orange mousse',
  'Sweetcorn and squash soup',
  'Rosemary and stilton gyoza',
  'Sole and persimmon dumplings',
  'Pineapple and potato soup',
  'Pigeon and trout soup',
  'Stilton and horseradish wontons',
];
List nonVegetarianStarterDescription = [
  'Tangy lime and kohlrabi combined into chunky soup',
  'Thin pastry cases stuffed with ricotta and mixed peppercorn',
  'Thin pastry cases stuffed with vintage cheese and pheasant',
  'A creamy mousse made with creamy cheese and blood orange',
  'Baby sweetcorn and fresh squash combined into smooth soup',
  'Thin pastry cases stuffed with dried rosemary and stilton',
  'Thin pastry cases stuffed with sole and fresh persimmon',
  'Fresh pineapple and new potato combined into chunky soup',
  'Pigeon and freshly-caught trout combined into creamy soup',
  'Thin wonton cases stuffed with stilton and fresh horseradish',
];
List nonVegetarianStarterIngredients = [
  'garlic | lime | kohlrabi',
  'flour | water | salt | onions | ricotta | peppercorn',
  'flour | water | salt | onions | cheese | pheasant',
  'egg | cream | onions | cheese | orange',
  'onion | sweetcorn | squash',
  'flour | water | salt | onions | rosemary | stilton',
  'flour | water | salt | onions | sole | persimmon',
  'garlic | pineapple | potato',
  'garlic | pigeon | trout | cream',
  'flour | water | salt | onions | stilton | horseradish',
];

List nonVegetarianMainMeal = [
  'Chicken and mutton curry',
  'Mutton and beef madras',
  'Chicken and beef casserole',
  'Chicken and beef korma',
  'Beef and chicken soup',
  'Beef and mutton stew',
  'Chicken and mutton vindaloo',
  'Chicken and beef burgers',
  'Beef and chicken stir fry',
  ' Beef and chicken pie',
];
List nonVegetarianMainMealDescription = [
  'Mild curry made with free range chicken and mutton',
  'Medium-hot madras made with mutton and beef',
  'Corn-fed chicken and beef stewed',
  'Creamy korma made with free range chicken and beef',
  'Beef and corn-fed chicken combined into creamy soup',
  'Beef and mutton stewed',
  'Spicy vindaloo made with free range chicken and mutton',
  'Succulent burgers made from corn-fed chicken and beef, served in a roll',
  'Crunchy stir fry featuring beef and corn-fed chicken',
  'A flaky pasty case filled with beef and free range chicken',
];
List nonVegetarianMainMealIngredients = [
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | curry leaf | green chilli | chicken | mutton',
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | red chilli | tomato | mutton | beef',
  'onion | salt | black pepper | potatoes | chicken | beef',
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | butter | sugar | cream | chicken | beef',
  'onion | beef | chicken | cream',
  'onion | salt | black pepper | potatoes | beef | mutton',
  'onion | peppers | garlic | ginger | tumeric | cumin | coriander | black pepper | mustard seeds | cardamon | cinnamon | white wine vinegar | cayenne | chicken | mutton',
  'flour | yeast | water | salt | sugar | oil | onions | chicken | beef',
  'peppers | beef | chicken',
  'flour | butter | water | salt | sugar | beef | chicken',
];
List nonVegetarianSnacks = vegetarianSnacks;
List nonVegetarianSnacksDescription = vegetarianSnacksDescription;
List nonVegetarianSnacksIngredients = vegetarianSnacksIngredients;
