
///both boy and girl name and sur name
List fullName = [
  'Quinn Huynh',
  'Isiah Hamilton',
  'Hobert Robinson',
  'Raleigh Solomon',
  'Erma Kidd',
  'Jacinto Chung',
  'Tommie Greene',
  'Hubert Bryant',
  'Tony Robles',
  'Janie Jarvis',
  'Sheryl Atkinson',
  'Jewell Ayala',
  'Patrica May',
  'Kelli Mosley',
  'Randolph Haynes',
  'Avis Sosa',
  'Mohammad Mooney',
  'Wade Holmes',
  'Wm Ortiz',
  'Lewis Levy',
  'Sasha Whitaker',
  'Hollie Saunders',
  'Elvia Bowman',
  'Eddy Huang',
  'Sebastian Short',
  'Pauline Mccoy',
  'Stacy Sullivan',
  'Steve Nolan',
  'Amado Fuller',
  'Quinton Wolf',
];

///boy and girls surname,
/// this is common for both boys and girls anyway
List surname = [
  'Hughes',
  'Hampton',
  'Holden',
  'Bates',
  'Brown',
  'Lamb',
  'Castro',
  'Parker',
  'Douglas',
  'King',
  'Hendricks',
  'Mcmillan',
  'Hester',
  'Everett',
  'Potter',
  'Haley',
  'Barnett',
  'Paul',
  'Odom',
  'Barber',
  'Kaufman',
  'Dalton',
  'Mason',
  'Rice',
  'Schroeder',
  'Mccullough',
  'Shields',
  'Herrera',
  'Chan',
  'Bowers',
  'Mccullough',
  'Mckenzie',
  'Holland',
  'Short',
  'Middleton',
  'Giles',
  'Cain',
  'Walton',
  'Patton',
  'Parrish',
  'Gamble',
  'Shields',
  'Thompson',
  'Bowers',
  'Fleming',
  'Cooley',
  'Miranda',
  'Evans',
  'Rodriguez',
  'Sellers',
  'Benitez',
  'Duffy',
  'Waller',
  'Zamora',
  'Shah',
  'Case',
  'Webster',
  'Choi',
  'White',
  'Goodman',
];

///boys and girls first name 
List firstName = [
  'Dollie',
  'Rowena',
  'Hector',
  'Lyndon',
  'Sheree',
  'Lino',
  'Magdalena',
  'Liliana',
  'Johnnie',
  'Carter',
  'Katie',
  'Jayson',
  'Priscilla',
  'Lenny',
  'Jewell',
  'Cecil',
  'Pearl',
  'Zachary',
  'Logan',
  'Tonya',
  'Lilia',
  'Tristan',
  'Roy',
  'Laurie',
  'Brooke',
  'Marcus',
  'Billie',
  'Aldo',
  'Abdul',
  'Betty',
];

List femaleFirstName = [
  'Charlene',
  'Carolyn',
  'Hillary',
  'Young',
  'Caroline',
  'Lenora',
  'Roxie',
  'Erica',
  'Sybil',
  'Natasha',
  'Carrie',
  'Charmaine',
  'Marion',
  'Cherry',
  'Freda',
  'Samantha',
  'Carissa',
  'Hallie',
  'Mona',
  'Laverne',
  'Charlotte',
  'Maude',
  'Avis',
  'Cara',
  'Gena',
  'Lillian',
  'Ilene',
  'Annabelle',
  'Queen',
  'Janie',
];

List maleFirstName = [
  'Luis',
  'Adan',
  'Josue',
  'Alberto',
  'Lemuel',
  'Grant',
  'Ronald',
  'Marquis',
  'Quentin',
  'Amado',
  'Winston',
  'Boyd',
  'Matthew',
  'Terrance',
  'Jerold',
  'Royce',
  'Angel',
  'Elijah',
  'Mario',
  'Fletcher',
  'Deangelo',
  'Chang',
  'Clifford',
  'Lamont',
  'Glen',
  'Emmitt',
  'Valentin',
  'Jackie',
  'Myles',
  'Lacy',
  'Demetrius',
  'Delbert',
  'Tobias',
  'Mark',
  'Nathanael',
  'George',
  'Coleman',
  'Lester',
  'Jules',
  'Renato',
  'Isiah',
  'Gail',
  'Freddie',
  'Yong',
  'Rodrigo',
  'Ralph',
  'Kieth',
  'Jerrod',
  'Lee',
  'Everett',
  'Homer',
];

List languages = [
  'Albanian',
  'Farsi',
  'Hindi',
  'Korean',
  'Polish',
  'Spanish',
  'English',
  'Arabic',
  'French',
  'Hmong',
  'Laotian',
  'Portuguese',
  'Tagalog',
  'Armenian',
  'German',
  'Italian',
  'Lithuanian',
  'Punjabi',
  'Thai',
  'Bengali',
  'Greek',
  'Japanese',
  'Malay',
  'Romanian',
  'Turkish',
  'Burmese',
  'Haitian',
  'Creole',
  'Karen',
  'Mandarin',
  'Russian',
  'Vietnamese',
  'Cantonese',
  'Hebrew',
  'Khmer',
  'Nepali',
  'Somali',
];

///Languages you don't even know exist
List otherLanguages = [
  'Acholi',
  'Afar',
  'Afrikaans',
  'Akan',
  'Akateko',
  'Albanian',
  'Amharic',
  'Anuak',
  'Apache',
  'Arabic',
  'Armenian',
  'Assyrian',
  'Azerbaijani',
  'Bahasa',
  'Bahdini',
  'Bahnar',
  'Bajuni',
  'Bambara',
  'Bantu',
  'Barese',
  'Basque',
  'Bassa',
  'Belorussian',
  'Bemba',
  'Benaadir',
  'Bengali',
  'Berber',
  'Bosnian',
  'Bravanese',
  'Bulgarian',
  'Burmese',
  'Cantonese',
  'Catalan',
  'Cebuano',
  'Chaldean',
  'Chamorro',
  'Chaochow',
  'Chin Falam',
  'Chin Hakha',
  'Chin Mara',
  'Chin Matu',
  'Chin Senthang',
  'Chin Tedim',
  'Chipewyan',
  'Chuukese',
  'Cree',
  'Croatian',
  'Czech',
  'Danish',
  'Dari',
  'Dewoin',
];
List jobOrOccupation = [
  'Fiberglass Fabricator',
  'Economic Development Specialist',
  'Concrete Mixer Driver',
  'Russian Language Professor',
  'Home Theater Installer',
  'Highway Engineering Technician',
  'Auto Clutch Rebuilder',
  'Parts Clerk',
  'Penologist',
  'Marine Technician',
  'Postsecondary Career and Technical Education Teacher',
  'Medical Records Specialist',
  'Desktop Publishing Specialist',
  'Train Clerk',
  'Animal Scientist',
  'Beveling and Edging Machine Operator',
  'Satellite Dish Installer',
  'Mechanical Design Drafter',
  'Speech Clinician',
  'Forest Nursery Worker',
  'Job Estimator',
  'Inventory Control Clerk',
  'Personal Investment Adviser',
  'Meat Carver',
  'Information Systems Planner',
  'Talent Agent',
  'Boat Hop',
  'Sea-Air-Land Officer',
  'Hydroelectric Machinery Mechanic',
  'Electronic Musical Instrument Repairer',
  'Concrete Vault Maker',
  'Airdrop Systems Technician',
  'Mathematical Physicist',
  'Hotel Director',
  'Endoscopy Registered Nurse',
  'Kettle Fry Cook Operator',
  'Community Association Manager',
  'Jacquard Loom Weaver',
  'Joint Strategic Plans And Policy Officer',
  'Literacy Education Professor',
  'Electrical Estimator',
  'Dietetic Technician',
  'Automotive Glazier',
  'Pit Steward',
  'Memorial Marker Designer',
  'Tutor',
  'Educational Psychology Professor',
  'Master Plumber',
  'Domestic Maid',
  'Physical Anthropologist',
  'Bridge Crane Operator',
  'Greek Professor',
  'Health Equipment Servicer',
  'Anesthetist',
  'Tool Room Machinist',
  'Physical Therapy Technician',
  'Equipment Cleaner',
  'Fashion Designer',
  'Sheet Rock Applier',
  'Research Geologist',
  'Studio Model',
  'Logistics Manager',
  'Health Care Manager',
  'Alterations Sewer',
  'Meat Counter Worker',
  'Medical Orderly',
  'City Letter Carrier',
  'Seismologist',
  'Childcare Center Director',
  'Beach Lifeguard',
  'Explosive Ordnance Handler',
  'Certified Rehabilitation Counselor',
  'Building Cleaning Supervisor',
  'Forest Biometrics Professor',
  'Fish Filleter',
  'Anodizer',
  'Paper Conservator',
  'Wood Carver',
  'Submarine Vertical Launch System Tube Maintenance Technician',
  'Public Health Dietitian',
  'Hand Model',
  'Gem Cutter',
  'Underwriting Service Representative',
  'Statistical Clerk',
  'Dental Surgeon',
  'Trombonist',
  'Air Support Control Officer',
  'Urban Forester',
  'Licensed Mental Health Counselor (LMHC)',
  'Orthopaedic Technologist',
  'Laboratory Animal Caretaker',
  'New Client Banking Services Clerk',
  'Time Study Technician',
  'Churn Driller',
  'Assembly Instructions Writer',
  'Ordnance Engineer',
  'Apartment Manager',
  'Attorney At Law',
  'Oilfield Plant and Field Operator',
  'Physical Biochemist',
];

///A List of nickname
List nicknames = [
'OompaLoompa',
'Weirdikan',
'Pecantruck',
'SnakerZizou',
'GatorXl',
'LoosetoothMl',
'Rosie',
'Goblin',
'Hot Pepper',
'Senorita',
'Biscuit',
'Sultan',
'Snoopyzz',
'DieselCayser',
'BunnyRabbit',
'Princess',
'Huggie',
'BigNasty',
'Cheeky',
'ButtonKamelK',
'Skunk',
'MooseXls',
'QueenBee',
'BugMezy',
'Rosebudlu',
];


