List hotelName = [
'Able Day Hotel',
'Bourbon Bliss',
'Candlewood Suites',
'Dream Connect',
'Enchanted Isle',
'Freehand',
'Green Acres',
'Harbor Court Hotel',
'Hotel Emblem',
'Hotel Joy Stick',
'Hotel The Pie',
'Jade Mountain',
'Millennium Times Square',
'Obsidian Sky',
'Parallel Tower',
'Prestige Proga Inn',
'Red Lion Hotel',
'Row Hotel',
'Sea Horizon',
'Sizzling inn',
'Soft Petal',
'Sunny Canopy',
'The Clift Royal',
'The Enchanted Garden',
'The Maxwell',
'The New View',
'The Quest Suites',
'The Standard High Line',
'The Upper House',
'Tiny Digs Hotel',
'Urban Boutique Hotel',
'Woodlark',
'Aloft Chicago',
'Cabrillo Inn & Suites',
'Classio Hotel',
'Denali Perch Resort',
'Embassy Suites',
'Fitzgerald Hotel',
'Four Seasons Hotel Gresham Palace',
'Grand Hotel',
'Hampton Inn & Suites',
'Holiday Inn Express',
'Homewood Suites',
'Hotel Lemonade',
'Inn of Chicago',
'Knights Inn',
'Lexington',
'London House',
'Oxford Suites',
'Parker New York',
'Quality Suites',
'Radisson Hotel',
'Rodeway Inn',
'The Bay Club',
'The Cartwright Hotel',
'The Houstonian Hotel',
'The James New York',
'The Manhattan',
'The Mississippi Hotel',
'The New Yorker',
'The Orchard Hotel',
'The Park Central',
'The River Hotel',
];


List hospitalName = [
'Newlife hospital',
'Care & Cure Hospital',
'Medwin Cares',
'Remedy plus care',
'Flowerence ',
'Rejuvenate',
'Health Object  Hospital',
'Mankind Medicare',
'Delight Sun CLinic',
'Ultra Care House',
'Ace hospital',
'HealthyWave',
'NorthMark',
'Hestinn Hospital',
'wellHue Hospital',
'BioNeu care',
'GoodAce care',
'HealthStreet',
'Good Planet',
'YouHeal Hospital',
'Redstar Hospital',
'True life care',
'Another life Hospital',
'Flowerflake Clinic',
'Crest care',
'Mercy medicare',
'Twin Tulip Hospital',
'One Health Clinic',
'lifeflash Clinic',
'Harmony',
'Midsummer Premium Hospital',
'safewest hospital',
'Mr.native Hospital',
'Wake up Medicare',
'Winter warm',
'Spring Hill care',
'Angelwalk Hospital',
'West valley hospital',
'The Tranquil',
'Angelcare hopsital',
'Hope Hospital',
'Intense Hospital',
'Soulbless Hospital',
'Grace Clinic',
'Willow Green Hospital',
'sacred Sprash Care',
'Forest vale care',
'Healthywing Clinic',
'Summer spring Hospital',
'Springedge Care',
'White valley care',
'Stonefield clinic',
'Hopewell Hospital',
'Loveable CLinic',
'Well and Good Clinic',
'Maple heart care',
'Highland Hospital',
'Goldriver Hospital',
'Future strong Memorial Hospital',
'Mr.Nine’s Hospital',
'A better healthcare',
'Health haven Hospiria',
'Al Shadow care',
'Let Live medicare',
'Britishcrew Hospital',
'Spirit Up care',
'lovely life medicenter',
'Happy space’s Hospital',
'GoldFish Hospital',
'LifeShades Hospital',
'HealVibe Hospital',
'WishyWave Hospital',
'MayLove Hospital',
'SilverCrest Hospital',
];
List mallName = [
'Arizona Mills',
'Arrowhead Towne Center',
'Biltmore Fashion Park',
'Chandler Fashion Center',
'Christown Spectrum Mall',
'Desert Ridge Marketplace',
'Desert Sky Mall',
'El Con Mall',
'Estrella Falls',
'Fiesta Mall',
'Foothills Mall',
'Kierland Commons',
'La Encantada',
'Los Arcos Mall',
'Mall at Sierra Vista',
'Mesa Riverview',
'Metrocenter Mall',
'Paradise Valley Mall',
'Park Place',
'SanTan Village',
'Scottsdale Fashion Square',
'Superstition Springs Center',
'Tanger Outlets',
'Tempe Marketplace',
'Tri City Mall',
'Tucson Mall',
];
List schoolName = [
'Success Academy',
'Academia Technologica',
'Scholars Institute	',
'Brain Train Academy',
'Advantage Academy',	
'Worldview Institute',
'Possiblities Training Academy',
'Build For Success Institute',
'Bella Vista Institute',
];
List highSchoolName = 
[
'Amherst High Schools',
'Elm Creek High Schools',
'Gibbon High Schools',
'Kearney High Schools',
'Kearney West High School',
'Pleasanton High Schools',
'Ravenna High Schools',
'Shelton High Schools',
'Anselmo-Merna High Schools',
'Ansley High Schools',
'Arnold High Schools',
'Broken Bow High Schools',
'Callaway High Schools',
'Sargent High Schools',
];
List collegeAndUniversitiesName = [
'Stanford University',
'California Institute of Technology',
'Pomona College',
'Harvey Mudd College',
'Claremont McKenna College',
'University of Southern California',
'Scripps College',
'Occidental College',
'Soka University of America',
'Pepperdine University',
'Santa Clara University',
'Pitzer College',
'Thomas Aquinas College',
'University of San Diego',
'Westmont College',
'Loyola Marymount University',
'University of San Francisco',
'Binghamton University',
'NYS College of Agriculture and Life Sciences',
'NYS College of Ceramics',
'SUNY College of Environmental Science and Forestry',
'NYS College of Human Ecology',
'College of Optometry',
'NYS College of Veterinary Medicine',
'Downstate Medical Center',
'School of Industrial and Labor Relations',
'Stony Brook University',
'SUNY Polytechnic Institute',
'Upstate Medical University',
'Dean College',
'Labouré College',
'Urban College of Boston',
];
List localAdresses = [
'Newton Dairy Rd #LOT 61 Henderson, North Carolina(NC), 27537',
'111 N Main St Brooklyn, Michigan(MI), 49230',
'Rr 1 Rome, Pennsylvania(PA), 18837'
'4676 Squire DrNorthfield, Ohio(OH), 44067',
'811 Hawthorne AveEl Dorado, Arkansas(AR), 71730',
'7071 Balsam Row RdShawano, Wisconsin(WI), 54166',
'1104 Mcintyre CirMarion, South Carolina(SC), 29571',
'92 Ball Yard HolwWhitesburg, Kentucky(KY), 41858',
'18561 Lime CirFountain Valley, California(CA), 92708',
'336 Hopkins RdBethel Springs, Tennessee(TN), 38315',
'5178 Moser LnPerrysburg, Ohio(OH), 43551',
'1784 S 15th StOzark, Missouri(MO), 65721',
'133 High StSouth Paris, Maine(ME), 04281',
'604 120th AveMartin, Michigan(MI), 49070',
'5872 Avenida JineteBonsall, California(CA), 92003',
'25 Drew AveNew Bloomfield, Pennsylvania(PA), 17068',
'17309 Eggers PlAbingdon, Virginia(VA), 24210',
'730 Pennbrooke St Owensboro, Kentucky(KY), 42301',
'Po Box 20304 Waco, Texas(TX), 76702',
'530 Victoria Ct Temple, Georgia(GA), 30179',
'6855 W Shadow Lake Dr Circle Pines, Minnesota(MN), 55014',
'27 Clark Ave Northampton, Massachusetts(MA), 01060',
'2140 Grand Ave West Des Moines, Iowa(IA), 50265',
'309 Hill St Gladwin, Michigan(MI), 48624',
'4799 E 2800th NEden, Utah(UT), 84310',
'3546 Englewood Dr #APT 121 Lake Worth, Florida(FL), 33467',
'2780 W Stanley Pl Anaheim, California(CA), 92801',
'2823 Sunset Dr Granite City, Illinois(IL), 62040',
'8443 Twin Lake Rd NE Mancelona, Michigan(MI), 49659',
'7352 Emerson Ave Westminster, California(CA), 92683',
'1 B Opal Ct Barnegat, New Jersey(NJ), 08005',
'320 Russell Ln Long Lake, Minnesota(MN), 55356',
'1420 Jones Rd Yuba City, California(CA), 95991',
];
