
List fashionComment = [
  'I love this outfit',
  'Wooww so beautiful',
  'omg can you tell me where you boughts this ',
  'I am happy to be born in this generation, fashion is just amazing',
  'This!! this is just fabulous',
  'I live for fashion and your outfit is just stuning',
  'Hey you look so good in that !! i love you keep it up with the good work',
  'Hey you can follow me , i also dpost about fashion, Thank you ?',
  'I think you were born with fashion, you are just amazing at choosing clothes',
  'so eu... how much does this one costed you ?',
  'My God....',
  'This outfit looks so dull on you, you shouldn\' wear this kind of outfit',
  'I don\'t like your look today, what happened ?',
  'Looks so bad, I can\'t even bring myself to press the like button',
  'This looks like Kendal Jenner trying to look like Kim K',
  'How dare you be this pretty',
  'If I have a kid one day, I want him or her to have the same fashion sense as you, you are my idol',
  'My phone is on fire',
  'I want this one',
  'Hey!! i saw this the other day... It was around \$980'
];
List technologyComment = [
  'i want an essay explaining why in god\'s name anyone would ever in their entire life need 384GB of RAM',
  'It\'s impressive that they found space for a headphone jack',
  'why am i even here, i dont even have enough money for this lmao',
  'I really really really need to see how this does processing Pix 4D data sets',
  'AMD threadripper 3970x has ~72 000 in geekbench',
  'Talking about 28 cores cpu and a whooping 384gb ram',
  'Finally something that can run an Android Studio and Chrome at the same time...',
  'Finally I see best machine for my Mario game :)',
  'Please compare the performance to the new Threadrippers from AMD.',
  'This is a very expensive puzzle. :)',
  'It had 342Gb of Ram.. who needs that much power',
  'I was thinking of buying one but thanks to you I will not do it anymore',
  'Well this is budget friendly',
  'After some days they will release the new AMD RealCore DragonX',
  'This phone looks amazing !!',
  'I tried this !1 the picture quality is just amazing',
  'You don\'t  even need to be smooth to use this thing, it does all the heavy lifting for you',
  'This is technology for the lazy.... i will buy it then since i am lazy',
  'What is your name ? how can you afford this expensive peace of amazing tech... I dream about having it,',
  'will  get one of these gadget for free if i create a YouTube chanel ? omg i really want one of thesse but i cannot afford it',
  'Just bought one of these for my Gf, well it is not working as expected... how exactly does the review say its good ?',
];
List foodReviewComment = [
  'Really loved the variety, taste, service Would actually rate it 4.5/5 . Half star deduction for not so clean cutlery. Even the desserts were so lovely, don\'t miss out on that for sure.',
  'Absolute barbecues is located on the ground floor of MGF Metropolis Mall, MG Road, Gurgaon. They serve Vegetarian and Non Vegetarian Food. The live grill is their speciality in which you will get chicken, mutton, fish, prawns etc. They also serve main course, dessert and alcoholic beverages too.We went their for team lunch. The staff behavior is average, they are not prompt. We took a little time to decide the drinks and the waiter got irritated. I ordered a piece of grilled chicken leg, which I never got. The grill was really hot and the food was getting burnt black in less than a minute.The outlet is pretty much clean and we\'ll maintained. You will also find counters for various food items for which you will have to walk up to the counter and it\'s not served on the table.',
  'This is for the first time that I went to this place.The desserts exceeded my expectations and you just cannot miss their crispy corn.Special shout out to Mr. Ajay Bhandari for his service. I don\'t think I have ever given individual shoutout. But, he was hospitality personified.',
  'When you get main course as good as starters, you know the buffet is a complete Paisa vasool.Went with my family last weekend and had loads of fun and food and good time.In starters, I loved the pineapple grill, mutton kebab, paneer Tikka, prawns and corn( Oh. They are the best I have had till date)For the main course, their biryani, papad with fresh curd is a must. Butter chicken is also very good and delish.',
  'We loved this place.. Absolute Carnival festival is going on.... They have lots of varieties in vaeg and non veg both... I like the the roasted Turkey and roasted Lamb... Ravioli was out standing...They have special counter for kids.. which had pasta in red and white sauce, yummy popcorn is also available there...Must visit this place and enjoy the food festival with your friends and family...Service was outstanding... Ambiance is very cool and cozy ...',
  'Similar to it\'s name, it is absolutely wonderful. Be it veg or nonveg everything was perfect. Variety of drinks, starter, dishes, food, dessert and moreover you can order non spicy food for kids. Tajel was our table coordinator and served very well. Anniversary cake was a real surprise :)',
  'Awesome! Awesome! Place for corporate lunch party! Pocket friendly, filling, variety and obviously desserts!!! I totally admire this place..It is fun, ambience is good and they added PANI PURI to the starters menu....Need I say more??',
  'A nice dineout place in MGF metropolis mall near MG Road Metro Station. The place usually have waiting in the evening.Talking about the ambience, the place is quite nice with great service and they make you eat so much and even serve the main course and desert at table only.No doubt the service is bang on.About the food, the starters have quite good variety and good in taste.I really liked the chilly potato ,corn and paneer tikka.The main course and desert is quite okay.Thus, the overall food experience is okay, but definitely the service and staff are really appreciating.',
  'Went dere on a office team lunch, it was all full and v got accommodated in few mins, though it was super busy but waiters were trying dere best to serve better.',
  'The experience was awesome.The bbq chckn,fish,mushroom was all good.Grilled vegetable would have been better.Desserts were good,unless an unwanted smell in the kheer of the rice.should include brownie in the desserts .Matar mushroom,fish kasundi,dal fry were awesome',
  'The place has a courteous and helpful staff. I went there for the first time and they explained me everything quite clearly. Their starters were average but their dahi kebabs and American cheesy potato were good. The mocktail was also amazing. They also have separate live grill, Mexican, pasta and chaat counters as well. Didn\'t like the red sauce pasta. Loved the quesadilla and tacos at the Mexican counter, their live grill concept and the chaats as well. I didn\'t like their main course though, most of the things lacked salt and the Chinese was really bad. Their desserts were amazing especially the ice creams, baked rasgulla and pastries.',
  'Great place for food lovers with varieties of veg and non veg items (chicken, prawn, fish, mutton). Taste, preparation and presentation is good. It\’s better to get table reserved in advance to avoid waiting. Appreciate their service & hospitality.',
  'This spot is the best smorgasbord café network in the world. The nourishment is extraordinary and the staff is extremely well mannered. I am not giving 5 stars on the grounds that the climate gets a little smokey in here because of the flame broils and it bothers in the eye. Aside from this everything is incredible. The cook even made uncommon chicken for us. Cherished the supper at this spot. Must attempt their paan kulfi ',
  'This is the perfect place to have full fledged lunch and dinners as there is a buffet system. I love their desserts, starters but i think there should be dome more variety of starters especially for the vegetarian menu. People often get bored with only limited options. As for the non veg option, everything was perfect',
  'This place is the best buffet restaurant chain here. The food is great and the staff is very polite. I am not giving 5 stars because the ambiance gets a little smokey in here due to the grills and it irritates in the eye. Apart from this everything is great. The chef even made special chicken for us. Loved the dinner at this place',
];
List hotelReviewComment = [
  'Our room in the loft was really cozy. the staff made us breakfast every day. their tips on how to get about town and beyond were spot on! they gave us weather predictions which were very useful in planning our day in a new city! We had a long chat about traveling and other things with our family. Wayne and Margie (2 staff) were really friendly and heartwarming!',
  'An excellent hotel with very good connectivity to the city.',
  'this place was lovely! The loft was beautiful, comfortable and had everything we needed.',
  'that place was wonderful so comfortable and welcoming Thoroughly enjoyed the stay',
  'It was a very warm welcome in this hotel, I felt like home. I enjoyed my stay and I recommend this place to everyone!',
  'Great place to stay',
  'Beautiful resort. We arrived pretty late at night and Wayne was there to greet us with a warm welcome. The resort is well kept and it\'s evident that every nook and corner was well thought out. The bed was super comfy and we rested well before our outings. Margie is super sweet and kind and thoughtful. We were treated very well like family and I would highly recommend this place to anyone visiting this country. The place is not far from the city and everything is easily accessible. Public transportation and cafes are easily accessible. The place is immaculate and pretty spotless. Breakfast and coffee was available every morning. Margie and Wayne were super helpful. We enjoyed our stay to the maximum. It was a home away from home experience. We would definitely return here on our next visit this country.',
  'Very clean, tidy and comfortable resort. The hosts are very kind, friendly and easygoing, they have prepared all of the things needed and help us check in really easily. Highly recommended and would love to return.',
  'What a beautiful modern home. the hosts were awesome! Our room was extremely comfy. They had berries and yogurt for breakfast and also made me coffee. So thoughtful and helpful! We stayed there after being on a cruise for 18 days and we were able to do laundry but @emilecode finished it for us and had it all folded nicely. They went above and beyond. If we come back I would stay here again in a heartbeat! Also, they gave us muffins and coffee to go before flying out!',
  'Lovely room and en-suite , hotel is spotless . Beautiful hotel close to shops / cafes .',
  'Great location, very peaceful and accessible. Delightful hosts, warm and welcoming. I look forward to returning.',
  'Sunshine Australian style villa.',
  'this resort was warm and welcoming. Beautiful breakfast, comfortable bed, and warm conversation.',
  'The hotel manager was very kind and sensitive host I won\'t forget!',
  'Thank you for having me stay. It was the perfect place to lay my head after a busy workshop at the nearby Castlecrag Steiner School. The room was perfect and the breakfast divine! Many thanks. Have already recommended to the school to put on their list for future visitors.',
  'Nice hotel. Had a comfortable stay.',
  'A fantastic place to stay in and also high privacy plus a great spacious area that guests will have, real place is actually better than the photos. It’s a must to choose',
  'Everything was perfect. The staff members are so kind and friendly, and the room was comfortable. The place is a little bit far from the city but it was peaceful and nice. Great place to stay!',
  'Fantastic place. highly recommend.',
  'I wanted to stay here due to the many wonderful reviews. Everything that has already been said is spot on. Such a warm friendly welcome followed by great conversation. The room, en-suite and little study are just wonderful. Due to work, I was not able to spend much time but I will definitely be staying again!',
  'the hotel staff members make u feel right at home. Almost like your part of their family. our room was so clean, comfy and beautiful. I liked the easy feeling of coming back from a day of adventure and sitting back with a glass of wine on the patio enjoying the evening breeze or sharing my day with some of them. They are genuinely interested in your holiday and extremely helpful with getting around and what to go see. When I return, which I will do someday. I WILL DEFINITELY STAY THERE AGAIN. They made the beginning of my world adventure really special. I almost didn\'t want to leave. I highly recommend you stay in that hotel and meet its staff members. Ps: @emilecode is an angel that goes above and beyond to personalize your stay.',
  'I spent 3 nights on this resort and I have to say this is the best resort I have ever stayed. emilecode and his staff are so kind and they made me feel like staying at home. They have their own daily routines so you don’t need to be unnatural and unrelaxed. You will have your private spaces and just feel free joining them from talking anytime. You will be treated as if you were their family member. And also every morning you can have a delicious breakfast (if you like to eat muesli, don’t forget to try emilecode\'s homemade one!!). emile and his staff are a lovely. They love travelling and they are passionate about life. Together We shared many stories on travelling. Actually sometimes I still feel nervous speaking English with Native speakers, but they made me relaxed and happy to chat with them. And they are very considerate. They keep an eye on weather changes and will get everything well prepared! The resort is nice looking just as the same on the photo. The place where it locates is quiet and safe, and I experienced the real life of local people these days. Although it is not in the city centre, don’t worry!! A 3min walk you will get to a bus station and the bus takes you to go straight to the centre in about 20min. This line takes you to almost all the big attractions! (And you can still catch it in late night) Everything is good. This resort staff makes me love more about the city. Thank you emilecode',
];
List carReviewComment = [
  'This car is amazing , i can\'t even feel the road when am inside',
  'The suspension greep is really good, i was driving at hight speed then i reached a bumb, i thought the car was gonna fly or do a small jump but no!! the suspension game did what it is supposed to do!!!',
  'That car... or whatever it is ... is very slow.. i would not recommend this',
  'This car engine is good, but the amount of gas consumed in a short amount of time is rediculous.. i won\'t advice this car if you don\'t have the money to take care of it ',
  'The interious is very luxious, it feels like a Rolls R.. well it\'s maybe it\s spirit inside this car...',
  'The manual system lacks stability , moving the clutch is a pain...',
  'this car is what i wanted, I love evryting about it, it was worth saving for...',
  'They said that one guy/girl will marry his car one day... i think it is gonna be me',
  'the glass is very solid, i think a bullet cannot easily break it',
  'I had the same car, it is very confortable, i remember selling everything i had to buy this car and i spent 4 months sleeping inside it, well it was worth the advanture, trust me',
  'It makes me want to go to Rome',
  'this person made a video one day where 3 other people were staring at this one car..... ',
  'This is the most italian thing ever made',
  'Whoever you are, if you own this car, please let me steal it from you',
  'This car looks like a mixture of Aston Martin and Porsche',
  'If Porsche and Aston Martin had a child that would be it ',
  'Beautiful Car , beautiful people, beautiful city, beautiful music, beautiful video. Everything is so buetifull here',
  'That is the worse thing i have ever seen on a car... ',
  'This car.... it makes no sounds... is it even alive ?',
  'Nice car..',
  'Musk made electric cars,.... let us make flying cars please',
];
List musicReviewComment = [
  'Who listen to this song in 2020 like this comment',
  'this song is so underrated :(',
  'This song gave me chills',
  'Every time I listen to this music i get hiped up',
  'Proof that this artistcan write it\'s own music,this is too personal to be ghost written',
  'This is why I love you, you\'re so real, a real gangsta',
  'I don’t understand why this is not a single?',
  'You can hear the pain in that voice... So real',
  'I\'m crying  and twerking to because this is a nice song',
  'I accidently clicked on this music...best mistake EVER',
  'I want more songs like this !!',
  'This song makes me wanna go smack my teacher and put her in detention',
  'This is my success motivation anthem. I play this everyday.',
  'thing song is PURE. all you need to know about this artist is here.',
  'I swear this song is underrated. This song should be on the charts!! it is fire..',
  'I SNAPPED on this track',
  'Bro I got a tattoo of this song - that’s how deep this hit me',
  'I did not like the song at all',
  'All respect to the artist. Don\'t matter what you came up from, a come up is a come up',
  'The lyrics are so true, it is just inspiring',
  'Maaaaaaannn, Damn I felt this song in my chest!!',
  'After that altercation, this song is even more better.',
  'We need a video for this song please.. this is fire',
  'This song is pain and strength at the same time',
  'This song gives me chills and hope! 2020 is going to be my year! Watch! I\'ll come back later with a update',
];

List socialMediaProfileDBio = [
  'I am a 27-year-old intelligence researcher who enjoys meditation, watching television and painting. i am kind and brave, but can also be very standoffish and a bit untrustworthy.',
  'I am an 18-year-old teenager who enjoys golf, football and swimming. Gentle and stable, but can also be very unstable and a bit dull. I am Swedish who defines myself as straight. I am currently at school. Physically, I am in pretty good shape with an average-height with bronze skin, brown hair and yellow eyes.',
  'I am a 26-year-old admin assistant who enjoys photography, biking and swimming. I am entertaining and brave, but can also be very selfish and a bit violent. I grew up in a working-class neighbourhood. Having never really known my parents, I was raised in a series of foster homes.',
  'I am a 61-year-old senior programmer who enjoys jigsaw puzzles, learning new languages and travelling. I am inspiring and smart, but can also be very cowardly and a bit rude. I am currently in a relationship with Kaitlyn Alma Wilkinson. Kaitlyn is 12 years older than me and works as a senior architect.',
  'I am a twelve-year-old child who enjoys writing, worship and going to the movies. I am considerate and creative, but can also be very standoffish and a bit selfish.I am an Australian Christian, currently at school.I live in an upper-class neighbourhood. my father passed away 11 years ago, leaving my mother, a builder Sienna, to look after me.',
  'I am a 26-year-old semi-professional sports person who enjoys social card games, attending galleries and extreme ironing. I am loveable and kind, but can also be very unintelligent and a bit sadistic. Physically, I am in pretty good shape. I have an average-height with pale skin, black hair and brown eyes.',
  'I am an eight-year-old child who enjoys hockey, golf and jigsaw puzzles. I am friendly and smart, but can also be very cowardly and a bit violent.I am an Irish Sikh. I am currently at school. I am allergic to wool and obsessed with Star Wars.Physically, I am in pretty good shape. I have an average-height for my age with bronze skin, red hair and green eyes.I live in a middle-class neighbourhood. My mother walked out 5 years ago, leaving my father, a pickpocket called Lucas, to look after me',
  'Stealing videos that I find interesting to me! I\'m picky!',
  'Welcome to my profile, i love memes',
  'Coding -> sleeping -> video games and sleep',
  'I love oreo, don\'t follow me if you don\'t',
  'Music has been part of my life since i started feeling lonely, moslty if you contact me, make sure you listen to Adele',
  'Don\'t judge me based on my pictures, I am more interesting once you get to know a lil bit more about me',
  'I am an Anime Addict, Naruto and Bleach are my favorite , folllow me at @emilecode for more info',
  'I make plugins for developers and i love helping the community, meme fan',
  'My life is all about cute girls , no cutes girls and i am out',
  'Whos said that reading was a bad habbit? i love reading and i did read lots of books, please contact me if reading is one of your favorite activity',
  'I am here for friendship only, nothing more',
  'I am a grammar nazy , Please do not text me like << Wts? >>, i do not reply to these type of messages',
  'I do business for a living and i have a familly that i love a lot',
  'Cold temperature is the best, i love snowboard and surfing, join me for more adventure,',
  'What is my name ? i do not know , what is yours ?',
  'Social media is bad, but we are all there right ? please do not judge me, let us have a pizza real quick and see if we connect ',
  'Well anime lover and music lover , i am into japanese stuffs',
  'I have no friends, i am not looking for more though , introvert but love netflix',
  'Can you share your Netflix account with me for free ? if yes please DM me',
  'I am a 14 year old addicted to tech, I am learning flutter and Iot, follow me to know more',
  'I make video games',
  'Who ? me ? you ? ... just follow me dear :) and Dm me for ollaboration',
  'Artist in the making here ! Dm me for collaboration and serious enquiries please',
  'Hey, I do not use this app so much can you please follow me at @emilecode on Instagram ? thanks :P',
  'Hi , I don\'t know why I am here, Let\'s plan something out :)', 
];
List randomComment = fashionComment + technologyComment+foodReviewComment+hotelReviewComment+carReviewComment+musicReviewComment;

List socialMediaPlatform = 
[
'Facebook',
'Youtube',
'instagram',
'Tumblr',
'Tik Tok',
'Twitter',
'Reddit',
'Linkedln',
'Medium',
];
